mod geometry;
mod simulation;
mod export;

use clap::Parser;

use geometry::Triangle;


use glam::Vec3;

use serde::Deserialize;
use simulation::SimulationConfig;
use std::fs;
use std::path::Path;
use std::time::Instant;


#[derive(Parser)]
#[command(name = "Acoustic Engine")]
#[command(about = "Multithreaded 3D acoustic raytracer", long_about = None)]
/// usage: cargo run --release -- --config-file input_config.json
struct Cli {
    /// Path to the JSON config file
    #[arg(short, long, default_value = "input_config.json")]
    config_file: String,
}


// Splits a rectangle into two triangles and appends them to the list.
fn add_rect_as_two_triangles(
    triangles: &mut Vec<Triangle>,
    a: Vec3, b: Vec3, c: Vec3, d: Vec3,
    absorption: f32,
) {
    triangles.push(Triangle { v0: a, v1: b, v2: c, absorption });
    triangles.push(Triangle { v0: a, v1: c, v2: d, absorption });
}


// Triangle data loadable from room_geometry.json (generated by obj_parser.py).
#[derive(Deserialize)]
struct TriangleData {
    v0: Vec3,
    v1: Vec3,
    v2: Vec3,
    absorption: f32,
}

#[derive(Deserialize)]
struct RoomGeometryFile {
    triangles: Vec<TriangleData>,
}


fn material_absorption(material: Option<&str>) -> f32 {
    match material {
        Some("concrete") => 0.033,
        Some("carpet")   => 0.425,
        Some("drywall")  => 0.150,
        Some("glass")    => 0.026,
        Some("foam")     => 0.650,
        _                => 0.200,
    }
}


fn main() {
    let cli = Cli::parse();

    println!("Reading config from: {}", cli.config_file);

    let config_text = fs::read_to_string(&cli.config_file)
        .expect("Could not read config file");

    let test_config: SimulationConfig = serde_json::from_str(&config_text)
        .expect("Could not parse simulation config (Is the JSON formatted correctly?)");



    // Raum-Geometrie laden: room_geometry.json (OBJ-Import via Python) wenn vorhanden,
    // sonst eingebauter 10x10x10m Würfel mit Material-basierter Absorption.
    let room: Vec<Triangle> = if Path::new("room_geometry.json").exists() {
        println!("Loading room geometry from room_geometry.json ...");
        let text = fs::read_to_string("room_geometry.json")
            .expect("Could not read room_geometry.json");
        let geom: RoomGeometryFile = serde_json::from_str(&text)
            .expect("Invalid room_geometry.json – run obj_parser.py to regenerate");
        println!("Loaded {} triangles from OBJ file.", geom.triangles.len());
        geom.triangles
            .into_iter()
            .map(|t| Triangle { v0: t.v0, v1: t.v1, v2: t.v2, absorption: t.absorption })
            .collect()
    } else {
        println!("No room_geometry.json – using built-in 10x10x10m box.");
        let absorption = material_absorption(test_config.wall_material.as_deref());
        let width = 10.0_f32;
        let depth = 10.0_f32;
        let height = 10.0_f32;
        let mut fallback: Vec<Triangle> = Vec::new();
        // Floor
        add_rect_as_two_triangles(&mut fallback, Vec3::new(0.0, 0.0, 0.0), Vec3::new(width, 0.0, 0.0), Vec3::new(width, depth, 0.0), Vec3::new(0.0, depth, 0.0), absorption);
        // Ceiling
        add_rect_as_two_triangles(&mut fallback, Vec3::new(0.0, 0.0, height), Vec3::new(width, 0.0, height), Vec3::new(width, depth, height), Vec3::new(0.0, depth, height), absorption);
        // Front wall
        add_rect_as_two_triangles(&mut fallback, Vec3::new(0.0, 0.0, 0.0), Vec3::new(width, 0.0, 0.0), Vec3::new(width, 0.0, height), Vec3::new(0.0, 0.0, height), absorption);
        // Back wall
        add_rect_as_two_triangles(&mut fallback, Vec3::new(0.0, depth, 0.0), Vec3::new(width, depth, 0.0), Vec3::new(width, depth, height), Vec3::new(0.0, depth, height), absorption);
        // Left wall
        add_rect_as_two_triangles(&mut fallback, Vec3::new(0.0, 0.0, 0.0), Vec3::new(0.0, depth, 0.0), Vec3::new(0.0, depth, height), Vec3::new(0.0, 0.0, height), absorption);
        // Right wall
        add_rect_as_two_triangles(&mut fallback, Vec3::new(width, 0.0, 0.0), Vec3::new(width, depth, 0.0), Vec3::new(width, depth, height), Vec3::new(width, 0.0, height), absorption);
        fallback
    };


    println!("Starting 3D parallel simulation");

    let start_parallel = Instant::now();

 
    let (delays_par, pressures_par) =
        simulation::run_simulation_parallel(&test_config, &room);

    let duration_parallel = start_parallel.elapsed().as_secs_f32();
    println!("Simulation run time: {} s", duration_parallel);

    export::export_results(delays_par, pressures_par, &test_config);

    let rays_to_visualize =
        simulation::run_simulation_visualizer(1, &test_config, &room);

    export::export_visualisation_data(rays_to_visualize, &test_config);
}